n_order: 7

m: 3

d_order: 4 # p v a j

LED_positions:
  - x: 0.085
    y: -0.075
    z: -0.030 #

PID_gain:
  - kp:
    - x: 0
      y: 0
      z: 0
      yaw: 0
  - ki:
    - x: 0
      y: 0
      z: 0
      yaw: 0
  - kd:
    - x: 0
      y: 0
      z: 0
      yaw: 0

