axis_dim: 3
n_order: 7
m: 2
d_order: 3 # p v a j

take_off_height: 0.4
landing_horizontal: 1.2
touch_down_height: 0.08
touch_down_offset: -0.0
ugv_height: 0.256


final_landing_x: 1.0

landing_velocity: 1.2

v_max: 4.0

a_max: 8.0

sample_square_root: 31

PID_gain:
#kp
  - x: 5.2
    y: 5.2
    z: 1.5
    yaw: 1.8
#ki
  - x: 0.6
    y: 0.6
    z: 0.05
    yaw: 0.05
#kd:
  - x: 1.6
    y: 1.6
    z: 0.05
    yaw: 0.0

