axis_dim: 3
n_order: 7
m: 2
d_order: 3 # p v a j

take_off_height: 0.4
landing_horizontal: 0.8
touch_down_height: 0.08
touch_down_offset: -0.0
ugv_height: 0.256

landornot: true

meetup_thres: 0.2

final_landing_x: 0.1

landing_velocity: 0.4

v_max: 4.0

a_max: 8.0

sample_square_root: 10

PID_gain:
#kp
  - x: 2.8
    y: 2.8
    z: 1.5
    yaw: 4.0
#ki
  - x: 0.5
    y: 0.5
    z: 0.05
    yaw: 0.05
#kd
  - x: 0.5
    y: 0.5
    z: 0.05
    yaw: 0.0

