axis_dim: 3
n_order: 7
m: 2
d_order: 3 # p v a j

take_off_height: 0.4
landing_horizontal: 1.0
touch_down_height: 0.14
touch_down_offset: -0.0
ugv_height: 0.254

landornot: false


final_landing_x: 0.8

landing_velocity: 1.2

v_max: 4.0

a_max: 8.0

sample_square_root: 31

PID_gain:
#kp
  - x: 9.1
    y: 9.1
    z: 1.5
    yaw: 4.0
#ki
  - x: 0.5
    y: 0.5
    z: 0.05
    yaw: 0.05
#kd
  - x: 1.0
    y: 1.0
    z: 0.05
    yaw: 0.0

