n_order: 7

m: 3

d_order: 4 # p v a j

take_off_height: 0.8
ugv_height: 0.259


final_landing_x: 1.0

landing_velocity: 1.2

v_max: 2.0

a_max: 4.0


PID_gain:
  - kp:
    - x: 0
      y: 0
      z: 0
      yaw: 0
  - ki:
    - x: 0
      y: 0
      z: 0
      yaw: 0
  - kd:
    - x: 0
      y: 0
      z: 0
      yaw: 0

