axis_dim: 3
n_order: 7
m: 2
d_order: 3 # p v a j

take_off_height: 0.4
landing_horizontal: 1.2
touch_down_height: 0.12
ugv_height: 0.256


final_landing_x: 1.0

landing_velocity: 1.2

v_max: 4.0

a_max: 8.0

sample_square_root: 31

PID_gain:
#kp
  - x: 3.75
    y: 3.75
    z: 1.5
    yaw: 1.2
#ki
  - x: 0.1
    y: 0.1
    z: 0.1
    yaw: 0.05
#kd:
  - x: 0.1
    y: 0.1
    z: 0.1
    yaw: 0.0

